Models/CategoryViewModel.cs
using Umbraco.Cms.Core.Models.PublishedContent;

namespace DenKhangThinh.Models;

public class CategoryViewModel
{
    public bool IsCategory { get; set; }
    public IPublishedContent Data { get; set; }
}

Models/PackageViewModel.cs
using Umbraco.Cms.Core.Models.PublishedContent;

namespace DenKhangThinh.Models;

public class PackageViewModel
{
    public bool IsPackage { get; set; }
    public IPublishedContent Data { get; set; }
}

Models/ProductViewModel.cs
using Umbraco.Cms.Core.Models.PublishedContent;

namespace DenKhangThinh.Models;

public class ProductViewModel
{
    public ProductViewModel()
    {
        IsFullWidth = false;
        ColumnWitdh = "w-6/12";
    }
    public bool IsHome { get; set; }
    public bool IsFullWidth { get; set; }
    public string ColumnWitdh { get; set; }
    public IPublishedContent? Data { get; set; }
}

Models/Search/SearchRequestModel.cs
namespace DenKhangThinh.Models.Search;

public class SearchRequestModel
{
    public string? Query { get; set; }
    public int Page { get; set; }
    public int PageSize { get; set; }
    public int Skip => Page > 1 ? (Page - 1) * PageSize : 0;


    public SearchRequestModel(string? query, string? page, int pageSize)
    {
        Query = query;

        if (int.TryParse(page, out int pageNumber) && pageNumber > 0)
        {
            Page = pageNumber;
        }

        PageSize = pageSize;
    }
}

Models/Search/SearchResponseModel.cs
using Examine;

namespace DenKhangThinh.Models.Search;

public class SearchResponseModel
{
    public bool HasResults => TotalResultCount > 0;
    public string? Query { get; set; }
    public long TotalResultCount { get; set; }
    public IEnumerable<ISearchResult>? SearchResults { get; set; }

    public SearchResponseModel() { }

    public SearchResponseModel(string? query, long totalResultCount, IEnumerable<ISearchResult>? searchResults)
    {
        Query = query;
        TotalResultCount = totalResultCount;
        SearchResults = searchResults;
    }
}

Models/ViewModels/ContactViewModel.cs
using DenKhangThinh.Validation;
using System.ComponentModel.DataAnnotations;

namespace DenKhangThinh.Models.ViewModels;

public class ContactViewModel
{
    [Display(Name = "Full name")]
    [Required(ErrorMessage = "You must enter your name")]
    public string? Name { get; set; }

    [Display(Name = "Email address")]
    [EmailAddress(ErrorMessage = "You must enter a valid email address")]
    [Required(ErrorMessage = "You must enter your email address")]
    public string? Email { get; set; }

    [Display(Name = "Phone number")]
    public string? Phone { get; set; }

    [Display(Name = "Message")]
    [Required(ErrorMessage = "You must enter your message")]
    public string? Message { get; set; }

    [Display(Name = "Yes, I give permission to store and process my data")]
    [Required(ErrorMessage = "You must give consent to us storing your details before you can send us a message")]
    [MustBeTrue(ErrorMessage = "You must give consent to us storing your details before you can send us a message")]
    public bool Consent { get; set; }
}

Components/PaginationViewComponent.cs
using DenKhangThinh.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace DenKhangThinh.Components;

[ViewComponent(Name = "Pagination")]
public class PaginationViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(PaginationViewModel model)
    {
        model ??= new PaginationViewModel();

        return View(model);
    }
}

Components/SearchResultsViewComponent.cs
using DenKhangThinh.Models.Search;
using Microsoft.AspNetCore.Mvc;

namespace DenKhangThinh.Components;

[ViewComponent(Name = "SearchResults")]
public class SearchResultsViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(SearchResponseModel model)
    {
        return View(model);
    }
}

Controllers/ContactController.cs
using DenKhangThinh.Models;
using DenKhangThinh.Services;
using DenKhangThinh.TemplateEngine;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using System.Net;
using System.Net.Mail;
using Umbraco.Cms.Core;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Common;
using Umbraco.Cms.Web.Website.Controllers;

namespace DenKhangThinh.Controllers;

public class ContactController : SurfaceController
{
    private readonly IPublishedContentQuery _contentQuery;
    private readonly IViewRenderService _viewRenderService;
    private readonly UmbracoHelper _umbracoHelper;
    private readonly IConfiguration _configuration;
    private readonly IWebHostEnvironment _environment;
    public ContactController(
        IUmbracoContextAccessor umbracoContextAccessor,
        IUmbracoDatabaseFactory databaseFactory,
        ServiceContext services,
        AppCaches appCaches,
        IProfilingLogger profilingLogger,
        IPublishedUrlProvider publishedUrlProvider,
        IPublishedContentQuery contentQuery,
        IViewRenderService viewRenderService,
        UmbracoHelper umbracoHelper,
        IConfiguration configuration,
        IWebHostEnvironment environment
        ) : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
    {
        _contentQuery = contentQuery;
        _viewRenderService = viewRenderService;
        _umbracoHelper = umbracoHelper;
        _configuration = configuration;
        _environment = environment;
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult HandleContactForm(ContactModel model)
    {
        Thread.CurrentThread.CurrentUICulture = new CultureInfo(model.CultureLcid);

        if (!ModelState.IsValid)
        {
            return Json(new
            {
                success = false,
                returnView = _viewRenderService.RenderToStringAsync("Contact/_Form", model),
                responseMessage = _umbracoHelper.GetDictionaryValue("Message.SendError") ?? "Đã có lỗi xảy ra trong quá trình gửi mail",
                responseType = _umbracoHelper.GetDictionaryValue("Title.Error") ?? "Thất bại"
            });
        }
        var textTemplate = new DotLiquidTemplate(Path.Combine(_environment.WebRootPath, "templates"));
        var sendTo = _configuration.GetValue<string>("EmailContactReceive") ?? "nhat05thud@gmail.com";
        var html = textTemplate.Render("EmailContact", new { name = model.Name, phone = model.Phone, service = model.Service });

        try
        {
            using (var message = new MailMessage("noreply@khangthinh.com", sendTo))
            {
                message.Subject = "Contact";
                message.Body = html;
                message.IsBodyHtml = true;
                using (var smtp = new SmtpClient())
                {
                    smtp.Host = "smtp.gmail.com";
                    smtp.EnableSsl = true;
                    var netCre = new NetworkCredential("mastersender002@gmail.com", "iyueomvxqokclgtp");
                    smtp.UseDefaultCredentials = false;
                    smtp.Credentials = netCre;
                    smtp.Port = 587;
                    smtp.Send(message);
                }
            }
        }
        catch (Exception ex)
        {
            throw;
        }

        model.Name = "";
        model.Phone = "";
        ModelState.Clear();

        return Json(new
        {
            success = true,
            returnView = _viewRenderService.RenderToStringAsync("Contact/_Form", model),
            responseMessage = _umbracoHelper.GetDictionaryValue("Message.SendSuccess") ?? "Gửi mail thành công",
            responseType = _umbracoHelper.GetDictionaryValue("Title.Success") ?? "Thành công"
        });
    }
}

Controllers/Render/SearchController.cs
using DenKhangThinh.Configuration;
using DenKhangThinh.Helpers;
using DenKhangThinh.Models.ContentModels;
using DenKhangThinh.Models.Search;
using DenKhangThinh.Models.ViewModels;
using DenKhangThinh.Services;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.Extensions.Options;

using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;

namespace DenKhangThinh.Controllers.Render;

public class SearchController : RenderController
{
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly ISearchService _searchService;
    private readonly SiteConfig _siteConfig;

    public SearchController(
        ILogger<RenderController> logger,
        ICompositeViewEngine compositeViewEngine,
        IUmbracoContextAccessor umbracoContextAccessor,
        IHttpContextAccessor httpContextAccessor,
        ISearchService searchService,
        IOptions<SiteConfig> siteConfig) : base(logger, compositeViewEngine, umbracoContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
        _searchService = searchService;
        _siteConfig = siteConfig.Value;
    }

    public override IActionResult Index()
    {
        var httpContext = _httpContextAccessor.HttpContext;
        var query = httpContext?.Request.Query[Constants.QueryStrings.Query];
        var page = httpContext?.Request.Query[Constants.QueryStrings.Page];

        if (CurrentPage == null) return BadRequest();

        var pageSize = _siteConfig?.SearchSettings?.PageSize ?? Constants.Search.DefaultPageSize;

        var searchRequest = new SearchRequestModel(query, page, pageSize);

        var searchResponse = _searchService.Search(searchRequest);

        var pagination = new PaginationViewModel
        {
            TotalResults = searchResponse.TotalResultCount,
            TotalPages = (int)Math.Ceiling((double)(searchResponse.TotalResultCount / searchRequest.PageSize)),
            ResultsPerPage = searchRequest.PageSize,
            CurrentPage = searchRequest.Page,
            PaginationUrlFormat = PaginationHelper.GetPaginationUrlFormat(Request.Path, Request?.QueryString.ToString(), page)
        };

        var model = new SearchPageContentModel(CurrentPage)
        {
            SearchRequest = searchRequest,
            SearchResponse = searchResponse,
            Pagination = pagination
        };

        return CurrentTemplate(model);
    }
}

Views/BlankPage.cshtml
@using Umbraco.Cms.Core.Models;
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
    var blankPage = (BlankPage)Model;
    var banner = blankPage.Banner;
}
@if (banner != null)
{
    <div class="about-banner">
        <img src="@(banner.GetCropUrl(1920,400, imageCropMode: ImageCropMode.Crop, furtherOptions: "&slimmage=true"))" alt="@blankPage.Name">
    </div>
}
else
{
    <div class="about-banner">
        <img src="https://placehold.co/1920x400" alt="@blankPage.Name">
    </div>
}
<div class="mgb-30"></div>
<div class="container">
    <h1 class="blog-title">@blankPage.Name</h1>
    <div class="wrap-content">
        @blankPage.Content
    </div>
</div>
<div class="mgb-30"></div>

Views/Category.cshtml
@using Umbraco.Cms.Core.Models;
@using DenKhangThinh.Models;
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits UmbracoViewPage<Category>
@{
    var home = Umbraco.AssignedContentItem.Root();
}
<h1 class="hidden-h1">@(home?.Value("metaTitle") ?? "")</h1>
@await Html.PartialAsync("Category/_CategoryItem", new CategoryViewModel { IsCategory = true, Data = Model})

Views/Contact.cshtml
@using DenKhangThinh.Models
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Contact>
@{
}
<div class="contact-info">
    <div class="flex flex-wrap justify-center w-full">
        <div class="maps">
            @Html.Raw(Model.GoogleMaps))
        </div>
        <div class="info wrap-main-info justify-center not-scale-image-left">
            @Model.ContactInfo
        </div>
    </div>
</div>
<div class="contact-form">
    <h2 class="text-center">@Model.FormTitle</h2>
    <div class="custom__width w-820">
        @await Html.PartialAsync("Contact/_Contact", new ContactModel { CultureLcid = System.Globalization.CultureInfo.CurrentUICulture.LCID, PageId = Model.Id })
    </div>
</div>

Views/Home.cshtml
@using DenKhangThinh.Models
@using Umbraco.Cms.Core.Models;
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Home>

<h1 class="hidden-h1">@(Model.MetaTitle ?? "")</h1>
@* @await Html.PartialAsync("Home/_HomeBanner") *@
@await Html.PartialAsync("Home/_HighLightProducts")
@await Html.PartialAsync("Home/_Categories")
@await Html.PartialAsync("Home/_Packages")
@await Html.PartialAsync("Home/_Benefit")

Views/Package.cshtml
@using DenKhangThinh.Models
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
}

@await Html.PartialAsync("Package/_PackageItem", new PackageViewModel { IsPackage = true, Data = Model })

Views/PackageItem.cshtml
@using DenKhangThinh.Models
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
}
@await Html.PartialAsync("Package/_PackageItem", new PackageViewModel { IsPackage = false, Data = Model })

Views/Packages.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
}
<div class="main-packages">
    @foreach (var item in Model.Children())
    {
        @await Html.PartialAsync("Layout/_PackageItem", item)
    }
</div>

Views/Product.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Cms.Core.Models;
@using DenKhangThinh.Helpers;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Product>
@{
    var home = Umbraco.AssignedContentItem.Root();
    var relatedImages = Model.RelatedImages ?? null;
}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="wd-breadcrumbs">
                <nav class="woocommerce-breadcrumb">
                    <a href="@home.Url()" class="breadcrumb-link">
                        Trang chủ
                    </a>
                    @foreach (var ancestor in Model.Ancestors().Where(t => t.IsVisible()).OrderBy(x => x.Level).Where(x => x.Level > 1))
                    {
                        <a href="@ancestor.Url()" class="breadcrumb-link">
                            @ancestor.Name
                        </a>
                    }
                    <span class="breadcrumb-last">@Model.Name</span>
                </nav>
            </div>
        </div>
        <div class="col-lg-6 col-12 col-md-6 product-images">
            <div class="product-images-inner">
                <div class="row">
                    <div class="col-lg-9 order-lg-last">
                        @if (Model.Sale > 0)
                        {
                            <div class="product-labels labels-rounded-sm"><span class="onsale product-label">-@(Model.Sale)%</span></div>
                        }
                        <div class="product-gallery__wrapper owl-carousel">
                            @foreach (var img in relatedImages)
                            {
                                <div class="product-image-wrap">
                                    <figure class="product-gallery__image">
                                        <a href="@img.Url()">
                                            <img width="800" height="800" data-large_image_width="800" src="@(img != null ? img.GetCropUrl(800, 800, imageCropMode: ImageCropMode.Crop, imageCropAnchor: ImageCropAnchor.Center, furtherOptions: "&slimmage=true") : $"https://placehold.co/800x800")" alt="@Model.Name" />
                                        </a>
                                    </figure>
                                </div>
                            }
                        </div>
                        <div class="product-additional-galleries">
                            <div class="wd-show-product-gallery-wrap wd-action-btn wd-style-icon-bg-text wd-gallery-btn"><a data-fancybox="gallery" href="@relatedImages.First().Url()" rel="nofollow" class="woodmart-show-product-gallery"><span>Click to enlarge</span></a></div>
                        </div>
                        <div class="hidden">
                            @foreach (var img in relatedImages.Skip(1))
                            {
                                <a data-fancybox="gallery" href="@img.Url()"></a>
                            }
                        </div>
                    </div>
                    <div class="col-lg-3 order-lg-first">
                        <div class="thumbnails slick-slider">
                            @foreach (var img in relatedImages)
                            {
                                <div class="product-image-thumbnail">
                                    <img width="150" height="150" src="@(img != null ? img.GetCropUrl(150, 150, imageCropMode: ImageCropMode.Crop, imageCropAnchor: ImageCropAnchor.Center, furtherOptions: "&slimmage=true") : $"https://placehold.co/150x150")" alt="@Model.Name" />
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @{
            var productSizes = Model.ProductSizes ?? null;
        }
        <div class="col-lg-6 col-12 col-md-6 text-left summary entry-summary">
            <div class="summary-inner set-mb-l reset-last-child">
                <h1 class="product_title wd-entities-title">@Model.Name</h1>
                <p class="price">
                    @if (Model.OldPrice > 0)
                    {
                        <del class="strike"><span class="amount"><bdi>@Utils.ToVnd(Model.OldPrice)</bdi></span></del>
                    }
                    @if (Model.Price > 0)
                    {
                        <ins class="highlight"><span class="amount"><bdi>@Utils.ToVnd(Model.Price)</bdi></span></ins>
                    }
                </p>
                @if (productSizes != null && productSizes.Any())
                {
                    <table class="woocommerce-product-attributes shop_attributes">
                        <tbody>
                            @foreach (ProductSize item in productSizes)
                            {
                                <tr class="woocommerce-product-attributes-item woocommerce-product-attributes-item--attribute_pa_bao-hanh">
                                    <th class="woocommerce-product-attributes-item__label">
                                        <span class="wd-attr-name">@item.Title</span>
                                    </th>
                                    <td class="woocommerce-product-attributes-item__value">
                                        <p>@item.Value</p>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                <div class="flexhouse-btn-wrap">
                    <a class="btn btn-4 btn-sep icon-send" target="_blank" href="@home?.Value("zaloLink")" style="background-color: rgb(162, 128, 21); color: rgb(255,255,255)">
                        <div class="icon">
                            <img width="40" height="40" src="/images/zalo-icon-1.png">
                        </div>
                        <span> &nbsp;Chat Zalo</span>
                    </a>
                    <a class="btn btn-4 btn-sep icon-send" target="_blank" href="tel:@home?.Value("phoneNumber")" style="background-color: rgb(162, 128, 21); color: rgb(255,255,255)">
                        <div class="icon">
                            <img width="40" height="40" src="/images/logo-cuoc-goi-new.png">
                        </div><span>&nbsp;Gọi cho tôi</span>
                    </a>
                </div>
                @* <div class="product_meta">
                    <span class="sku_wrapper">
                        <span class="meta-label">
                            Mã:
                        </span>
                        <span class="sku">
                            ZHS9013
                        </span>
                    </span>

                    <span class="posted_in"><span class="meta-label">Danh mục:</span> <a href="https://flexhouse.vn/den-trang-tri" rel="tag">Đèn trang trí</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/den-nang-luong-mat-troi" rel="tag">Đèn năng lượng mặt trời</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/den-trang-tri-ngoai-troi" rel="tag">Đèn trang trí ngoài trời</a></span>
                    <span class="tagged_as"><span class="meta-label">Từ khóa:</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/cot-den-chieu-sang" rel="tag">Cột đèn chiếu sáng</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/cot-den-nang-luong-mat-troi" rel="tag">Cột đèn năng lượng mặt trời</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/cot-den-san-vuon" rel="tag">Cột đèn sân vườn</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-chieu-sang-canh-quan" rel="tag">Đèn chiếu sáng cảnh quan</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-chieu-sang-nang-luong-mat-troi" rel="tag">Đèn chiếu sáng năng lượng mặt trời</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-chieu-sang-ngoai-troi" rel="tag">Đèn chiếu sáng ngoài trời</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-cot" rel="tag">Đèn cột</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-cot-ngoai-troi" rel="tag">Đèn cột ngoài trời</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-cot-san-vuon" rel="tag">Đèn cột sân vườn</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-cot-trang-tri" rel="tag">Đèn cột trang trí</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-ngoai-troi" rel="tag">Đèn ngoài trời</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/den-trang-tri-ngoai-san" rel="tag">Đèn trang trí ngoài sân</a><span class="meta-sep">,</span> <a href="https://flexhouse.vn/tu-khoa-san-pham/tru-den-chieu-sang" rel="tag">Trụ đèn chiếu sáng</a></span>
                </div> *@
            </div>
        </div>
    </div>
</div>
<div class="product-content-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="wrap-content-title">
                    <span>Mô tả</span>
                </div>
                <div class="wrap-content">
                    @Model.Description
                </div>
            </div>
        </div>
    </div>
</div>

Views/Search.cshtml
@using DenKhangThinh.Models;
@using Umbraco.Cms.Core.Models;
@inherits UmbracoViewPage<SearchPageContentModel>
@{
    var home = Umbraco.AssignedContentItem.Root();
    var searchPage = (Search)Model.Content;
    var banner = searchPage.Banner;
}
@if (banner != null)
{
    <div class="about-banner">
        <img src="@(banner.GetCropUrl(1920,400, imageCropMode: ImageCropMode.Crop, furtherOptions: "&slimmage=true"))" alt="@Model.Content.Name">
    </div>
}
else
{
    <div class="about-banner">
        <img src="https://placehold.co/1920x400" alt="@Model.Content.Name">
    </div>
}
<div class="mgb-30"></div>
<h1 class="hidden-h1">@(home?.Value("metaTitle") ?? "")</h1>
<h1 class="blog-title">@Model.Content.Name</h1>

<div class="container my-5">
    <div class="row">
        <div class="col-lg-9 col-12 mx-auto">
            @await Component.InvokeAsync("SearchResults", Model?.SearchResponse)

            @await Component.InvokeAsync("Pagination", Model?.Pagination)
        </div>
    </div>
</div>

Views/Type.cshtml
@using Umbraco.Cms.Core.Models;
@using DenKhangThinh.Models;
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
    var home = Umbraco.AssignedContentItem.Root();
}
<h1 class="hidden-h1">@(home?.Value("metaTitle") ?? "")</h1>
@await Html.PartialAsync("Category/_CategoryItem", new CategoryViewModel { IsCategory = false, Data = Model })